#!/bin/bash
clear
clear
#IZIN SCRIPT
MYIP=$(cat /usr/bin/.ipvps)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(cat /usr/bin/.ipvps)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(cat /usr/bin/.ipvps)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Smarasanta/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Sabdopalonstore"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6285161256106"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
IP=$(cat /usr/bin/.ipvps)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
clear
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97m SSH Ovpn Account \033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97m"
read -p " Username      : " Login
read -p " Password      : " Pass
read -p " Limit IP      : " iplimit
read -p " Limit Quota   : " Quota
read -p " Expired (Days): " masaaktif
echo -e "\033[0m"
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -wE "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
else
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
fi
clear

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>SSH OVPN Account     </code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Username         : </code> <code>$Login</code>
<code>Password         : </code> <code>$Pass</code>
<code>Limit Quota      : </code> <code>$Quota</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>IP               : $IP</code>
<code>Host             : </code> <code>$domain</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port SSH WS      : 80, 8080, 8081-9999 </code>
<code>Port SSH UDP     : 1-65535 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 400-900</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>SSH PORT 80      : </code><code>$domain:80@$Login:$Pass</code>
<code>SSH PORT 443     : </code><code>$domain:443@$Login:$Pass</code>
<code>SSH UDP          : </code><code>$domain:1-65535@$Login:$Pass</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Payload WSS      : </code><code>GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
OVPN Download : https://$domain:81/
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Info Script    : https://${domain}:81/
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Aktif Selama         : $masaaktif Hari
Dibuat Pada          : $tnggl
Berakhir Pada        : $expe
<code>◇━━━━━━━━━━━━━━━━━◇</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

clear
echo ""
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97m SSH OVPN Account \033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mUsername         : $Login\033[0m"
echo -e "\033[1;97mPassword         : $Pass\033[0m"
echo -e "\033[1;97mLimit Quota      : $Quota GB\033[0m"
echo -e "\033[1;97mLimit Ip         : ${iplimit} User\033[0m"
echo -e "\033[1;97mIP               : $IP\033[0m"
echo -e "\033[1;97mHost             : $domain\033[0m"
echo -e "\033[1;97mPort OpenSSH     : 443, 80, 22\033[0m"
echo -e "\033[1;97mPort SSH UDP     : 1-65535\033[0m"
echo -e "\033[1;97mPort Dropbear    : 443, 109\033[0m"
echo -e "\033[1;97mPort SSH WS      : 80, 8080, 8081-9999\033[0m"
echo -e "\033[1;97mPort SSH SSL WS  : 443\033[0m"
echo -e "\033[1;97mPort SSL/TLS     : 400-900\033[0m"
echo -e "\033[1;97mPort OVPN WS SSL : 443\033[0m"
echo -e "\033[1;97mPort OVPN SSL    : 443\033[0m"
echo -e "\033[1;97mPort OVPN TCP    : 443, 1194\033[0m"
echo -e "\033[1;97mPort OVPN UDP    : 2200\033[0m"
echo -e "\033[1;97mBadVPN UDP       : 7100, 7300, 7300\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mSSH Port 80      : $domain:80@$Login:$Pass\033[0m"
echo -e "\033[1;97mSSH PORT 443     : $domain:443@$Login:$Pass\033[0m"
echo -e "\033[1;97mSSH UDP          : $domain:1-65535@$Login:$Pass\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mPayload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mOVPN Download    : https://$domain:81/\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mInfo Script      : https://${domain}:81/\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mAktif Selama     : $masaaktif Hari\033[0m"
echo -e "\033[1;97mDibuat Pada      : $tnggl\033[0m"
echo -e "\033[1;97mBerakhir Pada    : $expe\033[0m"
