#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
NS=$( cat /etc/xray/dns )
PUB=$( cat /etc/slowdns/server.pub )
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(cat /usr/bin/.ipvps)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(cat /usr/bin/.ipvps)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Smarasanta/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Sabdopalonstore"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6285161256106"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 5
    reboot
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
source /var/lib/kyt/ipvps.conf
if [[ "$IP" = "" ]]; then
domain=$(cat /etc/xray/domain)
else
domain=$IP
fi
#tr="$(cat ~/log-install.txt | grep -w "Trojan WS " | cut -d: -f2|sed 's/ //g')"
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97m CREATE TROJAN ACCOUNT \033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"

read -rp "User: " -e user
user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

if [[ ${user_EXISTS} == '1' ]]; then
    clear
    echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
    echo -e "\033[1;97m CREATE TROJAN ACCOUNT \033[0m"
    echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
    echo ""
    echo "\033[1;97mA client with the specified name was already created, please choose another name.\033[0m"
    echo ""
    echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-trojan
fi
done

uuid=$(cat /proc/sys/kernel/random/uuid)
echo -e "\033[1;97m"
read -p "Expired (days): " masaaktif
read -p "Limit User (GB): " Quota
read -p "Limit User (IP): " iplimit
echo -e "\033[0m"
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`

# Update configuration files
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/trojan/ip
echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db

# Create Trojan account links
trojanlink1="trojan://${uuid}@bugkamu.com:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink="trojan://${uuid}@bugkamu.com:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
curl -s -o /dev/null -X POST "https://api.telegram.org/bot$KEY/sendMessage" \
-F chat_id="$CHATID" \
-F parse_mode="HTML" \
-F text="◇━━━━━━━━━━━━━━━━━◇
      TROJAN ACCOUNT
◇━━━━━━━━━━━━━━━━━◇
Remarks   : ${user}
Domain    : ${domain}
Limit Quota : ${Quota} GB
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : ${uuid}
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : trojan-grpc
◇━━━━━━━━━━━━━━━━━◇
TROJAN TLS
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink}</code>
◇━━━━━━━━━━━━━━━━━◇
TROJAN NTLS
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink2}</code>
◇━━━━━━━━━━━━━━━━━◇
TROJAN gRPC
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink1}</code>
◇━━━━━━━━━━━━━━━━━◇
Info Script    : https://${domain}:81/
◇━━━━━━━━━━━━━━━━━◇
Aktif Selama   : ${masaaktif} Hari
Dibuat Pada    : ${tnggl}
Berakhir Pada  : ${expe}
◇━━━━━━━━━━━━━━━━━◇"

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="<code>◇━━━━━━━━━━━━━━━━━◇
*_PEMBELIAN BERHASIL_*
◇━━━━━━━━━━━━━━━━━◇
-» PRODUK : TROJAN
-» REGION : $CITY
-» REQ CONFIG : 
-» REQ NAMA : $user
-» DEVICE : $iplimit IP
-» HARGA : 
-» AKTIF : $masaaktif HARI
-» TGL EXP : $expe
◇━━━━━━━━━━━━━━━━━◇
SABDO PALON STORE </code>"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
systemctl restart xray
clear
echo -e ""
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97m CREATE TROJAN ACCOUNT \033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mRemarks          : ${user}\033[0m"
echo -e "\033[1;97mHost/IP          : ${domain}\033[0m"
echo -e "\033[1;97mUser Quota       : ${Quota} GB\033[0m"
echo -e "\033[1;97mUser Ip          : ${iplimit} IP\033[0m"
echo -e "\033[1;97mPort             : 400-900\033[0m"
echo -e "\033[1;97mKey              : ${uuid}\033[0m"
echo -e "\033[1;97mXray Dns         : ${NS}\033[0m"
echo -e "\033[1;97mPubkey           : ${PUB}\033[0m"
echo -e "\033[1;97mPath             : /trojan-ws\033[0m"
echo -e "\033[1;97mServiceName      : trojan-grpc\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mLink WS          : ${trojanlink}\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mLink GRPC        : ${trojanlink1}\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mInfo Script      : https://${domain}:81/\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mAktif Selama     : $masaaktif Hari\033[0m"
echo -e "\033[1;97mDibuat Pada      : $tnggl\033[0m"
echo -e "\033[1;97mBerakhir Pada    : $expe\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
