#!/bin/bash
y='\033[1;33m'
f="\033[1;97;41m"
y='\033[1;33m' #yellow
UK='\e[38;5;99m'  # ungu jembut
WHITE="\033[1;37m"
RED="\e[91;1m"
GREEN='\033[0;32m'
NC='\e[0m'
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
export CHATID="6665982160"
export KEY="6829712716:AAE8Kfm8G7ndyFRQzzm19Z_ATiruGCF2VzI"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(cat /usr/bin/.ipvps)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(cat /usr/bin/.ipvps)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Smarasanta/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Sabdopalonstore"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6285161256106"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
echo -e "${UK}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y}${f}            MENU SHADOWSHOCKS            $NC"
echo -e "${UK}└──────────────────────────────────────────┘${NC}"
echo -e "${UK}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y}1.${NC}${WHITE} Create Account Shadowshocks WS/GRPC${NC}"
echo -e "  ${y}2.${NC}${WHITE} Create Trial Shadowshocks WS/GRPC${NC}"
echo -e "  ${y}3.${NC}${WHITE} Delete Account Shadowsocks WS/GRPC${NC}"
echo -e "  ${y}4.${NC}${WHITE} Renew Shadowsocks Account${NC}"
echo -e "  ${y}5.${NC}${WHITE} Check Shadowsocks login Account${NC}"
echo -e "  ${y}6.${NC}${WHITE} Check Config Shadowsocks  Account${NC}"
echo -e "${UK}└──────────────────────────────────────────┘${NC}"
echo -e ""
read -p "Select From Options [ 1 - 6 ] : " menu
case $menu in
1)
    addss
    ;;
2)
    trialss
    ;;
3)
    delss
    ;;
4)
    renewss
    ;;
5)
    cekss
    ;;
6)
    user-ss
    ;;   
 
*)
    menu
    ;;
esac