#!/bin/bash
y='\033[1;33m'
f="\033[1;97;41m"
y='\033[1;33m' #yellow
UK='\e[38;5;99m'  # ungu jembut
WHITE="\033[1;37m"
RED="\e[91;1m"
GREEN='\033[0;32m'
NC='\e[0m'
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
export CHATID="6665982160"
export KEY="6829712716:AAE8Kfm8G7ndyFRQzzm19Z_ATiruGCF2VzI"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(cat /usr/bin/.ipvps)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(cat /usr/bin/.ipvps)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Smarasanta/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Sabdopalonstore"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6285161256106"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
echo -e "${UK}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y}${f}               SSH & OPENVPN            ${NC}"
echo -e "${UK}└──────────────────────────────────────────┘${NC}"
echo -e "${UK}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y} 1.${NC}${WHITE} Create SSH & OpenVPN Account${NC}"
echo -e "  ${y} 2.${NC}${WHITE} Trial SSH & OpenVPN ${NC}"
echo -e "  ${y} 3.${NC}${WHITE} Renew SSH & OpenVPN ${NC}"
echo -e "  ${y} 4.${NC}${WHITE} Check User Login SSH & OpenVPN${NC}"
echo -e "  ${y} 5.${NC}${WHITE} Check User Login UDP${NC}"
echo -e "  ${y} 6.${NC}${WHITE} Daftar Member SSH & OpenVPN ${NC}"
echo -e "  ${y} 7.${NC}${WHITE} Hapus SSH & OpenVpn Account ${NC}"
echo -e "  ${y} 8.${NC}${WHITE} Hapus User Expired SSH & OpenVPN ${NC}"
echo -e "  ${y} 9.${NC}${WHITE} Autokill SSH Multi Login ${NC}"
echo -e "  ${y}10.${NC}${WHITE} Cek User Multi Login SSH ${NC}"
echo -e "  ${y}11.${NC}${WHITE} Config Ssh Account ${NC}"
echo -e "  ${y}12.${NC}${WHITE} Lock Ssh Account ${NC}"
echo -e "  ${y}13.${NC}${WHITE} Unlock Ssh Account ${NC}"
echo -e "  ${y}14.${NC}${WHITE} Limit On Off Ssh ${NC}"
echo -e "  ${y}15.${NC}${WHITE} Change Limit Ip SSH ${NC}"
echo -e "  ${y}16.${NC}${WHITE} Change Limit Quota SSH ${NC}"
echo -e "  ${y} x.${NC}${WHITE} Exit ${NC}"
echo -e "${UK}└──────────────────────────────────────────┘${NC}"
read -p "Select From Options [ 1 - 15 ] : " menu
echo -e ""
case $menu in
1)
    addssh
    ;;
2)
    trial
    ;;
3)
    renewssh
    ;;
4)
    cekssh
    ;;
5)
    cekudp
    ;;
6)
    member
    ;;
7)
    delssh
    ;;
8)
    delexp
    ;;
9)
    limit-ip-ssh
    ;;
10)
    ceklim
    ;;
11)
    user-ssh
    ;;
12)
    lock
    ;;
13)
    unlock
    ;;
14)
    limitssh-on-off
    ;;
15)
    ganti-ip
    ;;
16)
    ganti-quota
    ;;
*)
    menu
    ;;
esac