#!/bin/bash
y='\033[1;33m'
f="\033[1;97;41m"
y='\033[1;33m' #yellow
UK='\e[38;5;99m'  # ungu jembut
WHITE="\033[1;37m"
RED="\e[91;1m"
GREEN='\033[0;32m'
NC='\e[0m'
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
export CHATID="6665982160"
export KEY="6829712716:AAE8Kfm8G7ndyFRQzzm19Z_ATiruGCF2VzI"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# Getting
ipsaya=$(cat /usr/bin/.ipvps)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Smarasanta/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Sabdopalonstore"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6285161256106"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 5
    reboot
  fi
}
checking_sc
function Daftar_Account() {
grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq 
}
function member(){
clear
echo -e "\033[5;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "          MEMBER ACCOUNT VMESS                  "
echo -e "\033[5;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"      
echo "USERNAME         EXPAIRED          "
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
Daftar_Account
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
m-vmess
}
clear
echo -e "${UK}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y}${f}               MENU VMESS               $NC"
echo -e "${UK}└──────────────────────────────────────────┘${NC}"
echo -e "${UK}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y} 1.${NC}${WHITE} Creating Vmess Account WS/GRPC${NC}"
echo -e "  ${y} 2.${NC}${WHITE} Creating Trial Vmess Account WS/GRPC${NC}"
echo -e "  ${y} 3.${NC}${WHITE} Delete Vmess Account WS/GRPC${NC}"
echo -e "  ${y} 4.${NC}${WHITE} Renew Vmess Account${NC}"
echo -e "  ${y} 5.${NC}${WHITE} Check Vmess login Account${NC}"
echo -e "  ${y} 6.${NC}${WHITE} Member Vmess Account${NC}"
echo -e "  ${y} 7.${NC}${WHITE} Change Quota Account${NC}"
echo -e "  ${y} 8.${NC}${WHITE} Change Limit Ip Account${NC}"
echo -e "  ${y} 9.${NC}${WHITE} Check Config Vmess Account${NC}"
echo -e "  ${y}10.${NC}${WHITE} Lock Vmess Account${NC}"
echo -e "  ${y}11.${NC}${WHITE} Unlock Vmess Account${NC}"
echo -e "  ${y}12.${NC}${WHITE} Recovery Vmess Account${NC}"
echo -e "${UK}└──────────────────────────────────────────┘${NC}"
echo -e ""
read -p "Select From Options [ 1 - 12 ] : " menu
case $menu in
1)   clear ;
    addws
    ;;
2) clear ;
    trialws
    ;;
3) clear ;
    delws
    ;;
4) clear ;
    renewws
    ;;
5) clear ;
    cekws
    ;;
6) clear ;
	member 
	;;
7) clear ;
    change-vmess-qouta
    ;;
8) clear ;
    ganti-ip-vmess
    ;;
9) clear ;
    user-ws
    ;;
10) clear ;
    lock-vm
    ;;
11) clear ;
    unlock-vm
    ;;
12) clear ;
    recover-vm
    ;;
*) clear ;
    menu
    ;;
esac