#!/bin/bash 
# COLOR VALIDATION
clear
y='\033[1;33m' #yellow
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
f="\033[1;97;41m"
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g' | cut -d " " -f1-3)
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(printf '%(%H:%M:%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
clear
MYIP=$(cat /usr/bin/.ipvps)
echo ""
#########################
# USERNAME
Versi=$(cat /opt/.ver)
rm -f /usr/bin/user
get_data() {
    for i in {1..3}; do
        DATA=$(curl -fsSL --retry 3 --connect-timeout 5 "$1")
        [ ! -z "$DATA" ] && break
        sleep 1
    done
    echo "$DATA"
}

DATA_URL="https://raw.githubusercontent.com/Smarasanta/izin/main/ip"

DATA=$(get_data "$DATA_URL")

# Cari baris berdasarkan IP (kolom terakhir)
ROW=$(echo "$DATA" | awk -v ip="$MYIP" '$NF == ip')

if [ -z "$ROW" ]; then
    echo "IP tidak ditemukan!"
    exit 1
fi

set -- $ROW
username="$2"
exp="$3"       # tanggal expiry dari file izin
oid="$4"

# Simpan bila tetap ingin dipakai oleh script lain
echo "$username" >/usr/bin/user
echo "$exp" >/usr/bin/e
echo "$oid" >/usr/bin/ver

# -----------------------------
#   HITUNG SISA HARI
# -----------------------------
today=$(date +"%Y-%m-%d")

d1=$(date -d "$exp" +%s)
d2=$(date -d "$today" +%s)

# Selisih hari
certifacate=$(( (d1 - d2) / 86400 ))

# Fungsi date diff (kalau butuh)
datediff() {
    local x=$(date -d "$1" +%s)
    local y=$(date -d "$2" +%s)
    echo $(( (x - y) / 86400 ))
}

# -----------------------------
#   STATUS ACTIVE / EXPIRED
# -----------------------------
if [[ "$today" < "$exp" ]]; then
    sts="(${green}Active${NC})"
else
    sts="(${RED}ExpiRED${NC})"
fi

clear

# OS Uptime
uptime="$(uptime -p | cut -d " " -f 2-10)"
cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
cpu_usage+=" %"
DAY=$(date +%A)
DATE=$(date +%m/%d/%Y)
DATE2=$(date -R | cut -d " " -f -5)
IPVPS=$(curl -s ipinfo.io/ip )
cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
tram=$( free -m | awk 'NR==2 {print $2}' )
uram=$( free -m | awk 'NR==2 {print $3}' )
fram=$( free -m | awk 'NR==2 {print $4}' )
clear
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
#Status | Geo Project
clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="${green}[ON]${NC}"
else
   status_ssh="${red}[OFF]${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${green}[ON]${NC}"
else
    status_ws_epro="${red}[OFF]${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="${green}[ON]${NC}"
else
   status_haproxy="${red}[OFF]${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="${green}[ON]${NC}"
else
   status_xray="${red}[OFF]${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="${green}[ON]${NC}"
else
   status_nginx="${red}[OFF]${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="${green}[ON]${NC}"
else
   status_dropbear="${red}[OFF]${NC} "
fi
######################################
#####INFOAKUN
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
ssx=$(grep -c -E "^#ss# " "/etc/xray/config.json")
let ssa=$ssx/2
###########
nama="SABDO PALON STORE"
########
r="\033[1;31m"  #REDTERANG
a=" ${CYAN}ACCOUNT PREMIUM" 
# // ----->>> COLOR VALIDATIONS
KANAN="\033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m$NC"
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
WHITE="\033[1;37m"
CYAN="\033[96;1m"
BLUE="\033[4;34m"
RED='\033[0;31m'
NC='\033[0m'
green='\033[0;32m'
RED="\e[91;1m"
Blu_Cy="\e[5;36m"
# // color format 38
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # ungu jembut
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'
# // ----->>> COLOR VALIDATIONS
while true; do
    clear
    echo -e "   ${UK}┌──────────────────────────────────────────┐${Suffix}"
    echo -e "     ${y}${f}            SABDO PALON STORE           ${NC}"
    echo -e "   ${UK}└──────────────────────────────────────────┘${Suffix}"
    echo -e "   ${UK}┌──────────────────────────────────────────┐${Suffix}"
    echo -e "   ${UK}│$NC$r • $NC${z} System OS ${NC}     $y=$NC ${WHITE}$MODEL${NC}"
    echo -e "   ${UK}│$NC$r • $NC${z} Core System ${NC}   $y=$NC ${WHITE}$CORE${NC}"
    echo -e "   ${UK}│$NC$r • $NC${z} Server RAM ${NC}    $y=$NC ${WHITE}$tram MB $NC"
    echo -e "   ${UK}│$NC$r • $NC${z} Uptime Server ${NC} $y=$NC ${WHITE}$SERONLINE${NC}"
    echo -e "   ${UK}│$NC$r • $NC${z} Domain ${NC}        $y=$NC ${WHITE}$domain${NC}"
    echo -e "   ${UK}│$NC$r • $NC${z} IP VPS ${NC}        $y=$NC ${WHITE}$IPVPS${NC}"
    echo -e "   ${UK}│$NC$r • $NC${z} ISP ${NC}           $y=$NC ${WHITE}$ISP${NC}"
    echo -e "   ${UK}│$NC$r • $NC${z} City ${NC}          $y=$NC ${WHITE}$CITY${NC}"
    echo -e "   ${UK}│$NC$r • $NC${z} Date ${NC}          $y=$NC ${WHITE}$DATEVPS${NC}"
    echo -e "   ${UK}│$NC$r • $NC${z} Time ${NC}          $y=$NC ${WHITE}$TIMEZONE${NC}"
    echo -e "   ${UK}└──────────────────────────────────────────┘${Suffix}"
    echo -e "     ${r}────────────────────────────────────────${NC}"
    echo -e "     ${y}         SSH OVPN: $ssh1  VMESS: $vma ${Suffix}"
    echo -e "     ${y}      VLESS: $vla TROJAN: $trb SHADWSK: $ssa ${Suffix}"
    echo -e "     ${r}────────────────────────────────────────${NC}"
    echo -e "  ${UK}┌────────────────────────────────────────────┐${Suffix}"
    echo -e "  ${UK}│${Suffix} ${WHITE}SSH-WS :${Suffix} $status_ssh ${UK}│${Suffix} ${WHITE}XRAY :${Suffix} $status_xray ${UK}│${Suffix} ${WHITE}NGINX :${Suffix} $status_nginx ${UK}│${Suffix}"
    echo -e "  ${UK}└────────────────────────────────────────────┘${Suffix}"
    echo -e "  ${UK}┌────────────────────────────────────────────┐${Suffix}"
    echo -e "  ${UK}│$NC          ${WHITE}MENU SCRIPT TUNNELING             $NC${UK}│$NC"
    echo -e "  ${UK}│────────────────────────────────────────────│${NC}"
    echo -e "  ${UK}│$NC ${r}[${y}01${r}] ${WHITE}MENU SSH      ${UK}│$NC ${r}[${y}06${r}] ${WHITE}MENU SYSTEM      ${UK}│$NC"
    echo -e "  ${UK}│$NC ${r}[${y}02${r}] ${WHITE}MENU VMES     ${UK}│$NC ${r}[${y}07${r}] ${WHITE}CHACK BENDWITH   ${UK}│$NC"    
    echo -e "  ${UK}│$NC ${r}[${y}03${r}] ${WHITE}MENU VLESS    ${UK}│$NC ${r}[${y}08${r}] ${WHITE}SPEEDTEST        ${UK}│$NC"  
    echo -e "  ${UK}│$NC ${r}[${y}04${r}] ${WHITE}MENU TROJAN   ${UK}│$NC ${r}[${y}09${r}] ${WHITE}BACKUP/RESTORE   ${UK}│$NC"
    echo -e "  ${UK}│$NC ${r}[${y}05${r}] ${WHITE}MENU SS-R     ${UK}│$NC ${r}[${y}X.${r}] ${WHITE}EXIT             ${UK}│$NC"
    echo -e "  ${UK}└────────────────────────────────────────────┘${Suffix}"
    echo -e "      ${UK}┌────────────────────────────────────┐${Suffix}"
    echo -e "      ${UK}│$NC${z} Developer$NC      $y=$NC ${WHITE}SABDO PALON STORE"$NC
    echo -e "      ${UK}│$NC${z} Wa Contact$NC     $y=$NC ${WHITE}085161256106"$NC
    echo -e "      ${UK}│$NC${z} Version$NC        $y=$NC ${WHITE}${Versi}"$NC
    echo -e "      ${UK}│$NC${z} User$NC           $y=$NC ${WHITE}$username"$NC
    echo -e "      ${UK}│$NC${z} Script Status$NC  $y=$NC $sts "$NC
    echo -e "      ${UK}│$NC${z} Exp Script$NC     $y=$NC ${WHITE}$exp $certifacate Days$NC "$NC
    echo -e "      ${UK}└────────────────────────────────────┘${Suffix}"
    echo
    read -p " Select menu : " opt
    echo -e ""

    case $opt in
        1)
            clear
            m-sshws
            ;;
        2)
            clear
            m-vmess
            ;;
        3)
            clear
            m-vless
            ;;
        4)
            clear
            m-trojan
            ;;
        5)
            clear
            m-ssws
            ;;
        6)
            clear
            utility
            ;;
        7)
            clear
            bw
            ;;
        8)
            clear
            speedtest
            ;;
        9)
            clear
            menu-backup
            ;;
        x)
            clear
            figlet SABDO PALON | lolcat
            exit 0
            ;;
        r)
            clear
            figlet BYE BYE | lolcat
            reboot
            ;;
        0)
            clear
            figlet SABDO PALON | lolcat
            exit 0
            ;;
        *)
            echo -e "${RED}Input tidak valid!${NC} Silakan pilih menu yang benar."
            sleep 2
            ;;
    esac

    # Menunggu input sebelum kembali ke menu
    read -p "Tekan Enter untuk kembali ke menu..."
done
