#!/bin/bash

RED="\033[31m"
GREEN='\033[0;32m'
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(cat /usr/bin/.ipvps)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(cat /usr/bin/.ipvps)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Smarasanta/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Sabdopalonstore"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6285161256106"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 5
    reboot
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
domain=$(cat /etc/xray/domain)
masaaktif=1
Quota=1
iplimit=10
user=Trial-VL`</dev/urandom tr -dc 0-9 | head -c3`
clear 
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
clear
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
cat >/var/www/html/vless-$user.txt <<-END

◇━━━━━━━━━━━━━━━━━◇
SABDO PALON STORE
◇━━━━━━━━━━━━━━━━━◇
# Format Vless WS TLS

- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

# Format Vless WS Non TLS

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

# Format Vless gRPC (SNI)

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

◇━━━━━━━━━━━━━━━━━◇
Link Akun Vless 
◇━━━━━━━━━━━━━━━━━◇
Link TLS      : 
${vlesslink1}
◇━━━━━━━━━━━━━━━━━◇
Link none TLS : 
${vlesslink2}
◇━━━━━━━━━━━━━━━━━◇
Link GRPC     : 
${vlesslink3}
◇━━━━━━━━━━━━━━━━━◇
END

if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vless/ip
echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^#&" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "#& ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db
curl -s -o /dev/null -X POST "https://api.telegram.org/bot$KEY/sendMessage" \
-F chat_id="$CHATID" \
-F parse_mode="HTML" \
-F text="◇━━━━━━━━━━━━━━━━━◇
      VLESS ACCOUNT
◇━━━━━━━━━━━━━━━━━◇
Remarks   : ${user}
Domain    : ${domain}
Limit Quota : ${Quota} GB
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : ${uuid}
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : vless-grpc
◇━━━━━━━━━━━━━━━━━◇
 VLEES WS TLS
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink1}</code>
◇━━━━━━━━━━━━━━━━━◇
VLEES WS NO TLS
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink2}</code>
◇━━━━━━━━━━━━━━━━━◇
 VLEES gRPC
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink3}</code>
◇━━━━━━━━━━━━━━━━━◇
Format OpenClash : https://${domain}:81/vless-$user.txt
◇━━━━━━━━━━━━━━━━━◇
Aktif Selama   : $masaaktif Hari
◇━━━━━━━━━━━━━━━━━◇" 
systemctl restart xray
clear
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97m CREATE VLESS ACCOUNT \033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mRemarks     : ${user}\033[0m"
echo -e "\033[1;97mDomain      : ${domain}\033[0m"
echo -e "\033[1;97mUser Quota  : ${Quota} GB\033[0m"
echo -e "\033[1;97mUser Ip     : ${iplimit} IP\033[0m"
echo -e "\033[1;97mPort TLS    : 400-900\033[0m"
#echo -e "\033[1;97mPort DNS    : 443\033[0m"
echo -e "\033[1;97mPort NTLS   : 80, 8080, 8081-9999\033[0m"
echo -e "\033[1;97mUser ID     : ${uuid}\033[0m"
#echo -e "\033[1;97mXray Dns.   : ${NS}\033[0m"
#echo -e "\033[1;97mPubkey.     : ${PUB}\033[0m"
echo -e "\033[1;97mEncryption  : none\033[0m"
echo -e "\033[1;97mPath TLS    : /vless\033[0m"
echo -e "\033[1;97mServiceName : vless-grpc\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mLink TLS    : ${vlesslink1}\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mLink NTLS   : ${vlesslink2}\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mLink GRPC   : ${vlesslink3}\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mFormat OpenClash : https://${domain}:81/vless-$user.txt\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "\033[1;97mAktif Selama     : $masaaktif Hari\033[0m"
echo -e "\033[1;97mDibuat Pada      : $tnggl\033[0m"
echo -e "\033[1;97mBerakhir Pada    : $expe\033[0m"
echo -e "\e[38;5;99m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"

menu
