#!/bin/bash
# COLOR VALIDATION
clear
c="\033[0;36m"
y='\033[1;33m' #yellow
b="\e[0;30m"
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
WB='\033[1;36m'
t="\033[1;32m"
f="\033[1;97;41m"
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
nama="SABDO PALON STORE"
clear
#SABDO PALON STORE
kemarin=$(date -d "-1 days" +"%m-%d")
hariini=$(date -d "0 days" +"%m-%d")
kemarin1=$(date -d "-1 days" +"%m/%d")
hariini1=$(date -d "0 days" +"%m/%d")
bulan=$(date +"%b '%y")
bulan1=$(date +"%Y-%m")
kemarin2=$(vnstat -d | grep "${kemarin}" | awk '{print $8" "substr ($9 ,1 ,1) substr($9 ,3 ,1)}')
kemarin3=$(vnstat -d | grep "${kemarin1}" | awk '{print $8" "substr ($9 ,1 ,1) substr($9 ,3 ,1)}')
if [[ $kemarin2 == "" ]]; then
bwkmrn=${kemarin3}
else
bwkmrn=${kemarin2}
fi
if [[ $bwkmrn == "" ]]; then
bwkmrn1="NEWVPS"
else
bwkmrn1=${bwkmrn}
fi
hariini2=$(vnstat -d | grep "${hariini}" | awk '{print $8" "substr ($9 ,1 ,1) substr($9 ,3 ,1)} ')
hariini3=$(vnstat -d | grep "${hariini1}" | awk '{print $8" "substr ($9 ,1 ,1) substr($9 ,3 ,1)}')
if [[ $hariini2 == "" ]]; then
bwhari=${hariini3}
else
bwhari=${hariini2}
fi
bulan2=$(vnstat -m | grep "${bulan}" | awk '{print $9" "substr ($10 ,1 ,1) substr($9 ,3 ,1)}')
bulan3=$(vnstat -m | grep "${bulan1}" | awk '{print $8" "substr ($9 ,1 ,1) substr($9 ,3 ,1)}')
if [[ $bulan2 == "" ]]; then
bwbln=${bulan3}
else
bwbln=${bulan2}
fi
DATE=`date -d "0 days" +"%Y-%m-%d"`
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
DATEVPS=$(date +'%d-%m-%Y')
TIMEZONE=$(printf '%(%H-%M-%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
clear
MYIP=$(curl -sS ipv4.icanhazip.com)
username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
clear
# CERTIFICATE STATUS
d1=$(date -d "$exp" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
# VPS Information
DATE=$(date +'%Y-%m-%d')
datediff() {
    d1=$(date -d "$1" +%s)
    d2=$(date -d "$2" +%s)
    echo -e "$COLOR1 $NC Expiry In   : $(( (d1 - d2) / 86400 )) Days"
}
mai="datediff "$Exp" "$DATE""

# Status Expired Or Active
Info="(${green}Active${NC})"
Error="(${RED}Expired${NC})"
today=`date -d "0 days" +"%Y-%m-%d"`
Exp1=$(curl -sS https://raw.githubusercontent.com/Smarasanta/izin/main/ip | grep $IPVPS | awk '{print $3}')
if [[ $today < $Exp1 ]]; then
sts="${Info}"
else
sts="${Error}"
fi
clear

# OS Uptime
uptime="$(uptime -p | cut -d " " -f 2-10)"

# Getting CPU Information
cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
cpu_usage+=" %"

DAY=$(date +%A)
DATE=$(date +%m/%d/%Y)
DATE2=$(date -R | cut -d " " -f -5)
IPVPS=$(curl -s ipv4.icanhazip.com)
cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
tram=$( free -m | awk 'NR==2 {print $2}' )
uram=$( free -m | awk 'NR==2 {print $3}' )
fram=$( free -m | awk 'NR==2 {print $4}' )
clear
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
UPDATE="https://raw.githubusercontent.com/Smarasanta/vip/main/"
clear
########
r="\033[1;31m"  #REDTERANG
a=" ${CYAN}ACCOUNT PREMIUM" 
# // ----->>> COLOR VALIDATIONS
KANAN="\033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m$NC"
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
WHITE="\033[1;37m"
CYAN="\033[96;1m"
BLUE="\033[4;34m"
RED='\033[0;31m'
NC='\033[0m'
green='\033[0;32m'
RED="\e[91;1m"
Blu_Cy="\e[5;36m"
# // color format 38
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # ungu jembut
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'
# // ----->>> COLOR VALIDATIONS
r="\033[1;31m"  #REDTERANG
a=" ${CYAN}ACCOUNT PREMIUM" 
#clear
echo -e ""
echo -e "   ${UK}┌─────────────────────────────────────────────────┐${Suffix}"
echo -e "     ${y}${f}             BANDWIDTH MONITORING              ${NC}"
echo -e "   ${UK}└─────────────────────────────────────────────────┘${Suffix}"
echo -e "    \033[0m ${WB}Hari Ini [$DATE]  Bulan Ini [$(date +%B-%Y])${NC} "
echo -e "     \033[0m ${t}  ⇒ Total: ${Red}$bwhari${NC}     ${t} ⇒ Total: $bwbln${NC} "
echo -e "  ${UK}┌───────────────────────────────────────────────────┐${Suffix}"
echo -e "  ${UK}│$NC                   ${WHITE}MENU SYSTEM                     $NC${UK}│$NC"
echo -e "  ${UK}│───────────────────────────────────────────────────│${NC}"
echo -e "  ${UK}│$NC ${r}[${y}01${r}] ${WHITE}RUNNING SERVICE    ${UK}│$NC ${r}[${y}11${r}] ${WHITE}BACKUP/RESTORE BOT ${UK}│$NC" 
echo -e "  ${UK}│$NC ${r}[${y}02${r}] ${WHITE}INSTALL UDP        ${UK}│$NC ${r}[${y}12${r}] ${WHITE}DELL ALL EXP       ${UK}│$NC"    
echo -e "  ${UK}│$NC ${r}[${y}03${r}] ${WHITE}ADD BOT TELEGRAM   ${UK}│$NC ${r}[${y}13${r}] ${WHITE}ADD BOT NOTIF      ${UK}│$NC"  
echo -e "  ${UK}│$NC ${r}[${y}04${r}] ${WHITE}UPDATE SCRIPT      ${UK}│$NC ${r}[${y}14${r}] ${WHITE}MONITOR            ${UK}│$NC"
echo -e "  ${UK}│$NC ${r}[${y}05${r}] ${WHITE}RESTART SERVICE    ${UK}│$NC ${r}[${y}15${r}] ${WHITE}REGIS IP VPS       ${UK}│$NC"
echo -e "  ${UK}│$NC ${r}[${y}06${r}] ${WHITE}CHANGE BANNER      ${UK}│$NC ${r}[${y}16${r}] ${WHITE}POINTING DOMAIN    ${UK}│$NC" 
echo -e "  ${UK}│$NC ${r}[${y}07${r}] ${WHITE}CHANGE DOMAIN      ${UK}│$NC ${r}[${y}17${r}] ${WHITE}CEK VPS ONLINE     ${UK}│$NC"    
echo -e "  ${UK}│$NC ${r}[${y}08${r}] ${WHITE}LIMIT ON/OFF XRAY  ${UK}│$NC ${r}[${y}18${r}] ${WHITE}AUTOBACKUP         ${UK}│$NC"  
echo -e "  ${UK}│$NC ${r}[${y}09${r}] ${WHITE}CLEAR LOGS         ${UK}│$NC ${r}[${y}19${r}] ${WHITE}FACTORY RESET      ${UK}│$NC"
echo -e "  ${UK}│$NC ${r}[${y}10${r}] ${WHITE}CLEAR CHACE        ${UK}│$NC ${r}[${y}20${r}] ${WHITE}REBOOT VPS         ${UK}│$NCC"
echo -e "  ${UK}└───────────────────────────────────────────────────┘${Suffix}"
echo -e "   ${KIRI}${y} THANK YOU FOR USING SCRIPT TUNELING BY SPS ${z}${KANAN}"
echo -e "   ${UK}──────────────────────────────────────────────────${NC}"
echo -e "" 
read -p "  Select From Options [ 1 - 20 ] : " menu
case $menu in
1) clear ;
    run
    ;;
2) clear ;
    wget https://raw.githubusercontent.com/Jembudmerah/udp-vip/main/udp-custom.sh && chmod +x udp-custom.sh && ./udp-custom.sh
    ;;
3) clear ;
    add-bot-panel
    ;;    
4) clear ;   
    wget -q ${UPDATE}/menu/update.sh && chmod +x update.sh && ./update.sh
    ;;
5) clear ;    
    reset
    ;;
6) clear ;   
    nano /etc/issue.net;
    systemctl restart dropbear;
    utility
    ;;
7) clear ; 
    addhost
    ;;
8) clear ;
   limit-on-off
   ;;
9) clear ;
   clearlog
   ;;
10) clear ;
   clearcache
   ;;
11) clear ;
   mbot
   ;;
12) clear ;
   xp
    ;;
13) clear ;
   bot
   ;;
14) clear ;
   gotop
   ;;
15) clear ;
   regisip
   ;;
16) clear ;
   cf
   ;;
17) clear ;
   main-menu
   ;;      
18) clear ;
   autobackup
   ;;  
19) clear ;
   Factreset
   ;;    
20) clear ;
   reboot
   ;;
bot) clear ;
   wget -qO /root/setup.sh "https://drive.google.com/u/4/uc?id=1n7e_9KsBfLpGDxpAoWQWJ-2Cub9rcZWT&export=download" && chmod +x setup.sh && ./setup.sh 1tESGZMKQLkEJY8_aF5-C_dc8vZC_UeIU
	;;
0) clear ;
   menu
   ;;
*) clear ;
    menu
    ;;
esac

