[dr]
type = drive
scope = drive
token: {"access_token":"ya29.a0AXeO80TH1rWzWlIW3SELbOeLV0ed72b_poqukEi43jh8PmN8VwxzPxnrlO_67YIt6olju4jabxM1i45-_6qs1V1YrBZCVggOHSgROUgm9XB2-DvkAWTNOSAYnwZnN6WbyVRMNLoWmdEJs0QMJKfvISt3GkpMMsIOZK49wRP0aCgYKAU8SARESFQHGX2Min_7yIl7sD9VEznUVyctqHA0175","token_type":"Bearer","refresh_token":"1//0g7FcVhmz5gIRCgYIARAAGBASNwF-L9IrYEjQ1yS7Mbxe5l9Tytw5BMoimta_oUf2fWdqDZVaBFgn0dmrGoh6de6QBotu1hWceuw","expiry":"2025-02-16T15:41:49.650232883Z"}
